linters:
  presets:
    - bugs
    - comment
    - error
    - complexity
    - import
    - test
    - unused
  disable:
    - depguard
    - exhaustruct
    - funlen
linters-settings:
  mnd:
    ignored-numbers:
      - 0666
      - 0750
  testifylint:
    enable-all: true
